# Enable Pyflakes and pycodestyle rules.
select = ["E", "F"]

# Never enforce `E501` (line length violations). E402:Module level import not at top of file
ignore = ["E501", "E402","F403","F405"]

# Always autofix, but never try to fix `F401` (unused imports).
fix = true
unfixable = ["F401"]

# Ignore 
[per-file-ignores]
"pkscreener/globals.py" =["F841", "E712"]
"pkscreener/classes/ParallelProcessing.py" =["F841"]
"pkscreener/classes/Utility.py" = ["F401"]