# """
#     The MIT License (MIT)

#     Copyright (c) 2023 pkjmesra

#     Permission is hereby granted, free of charge, to any person obtaining a copy
#     of this software and associated documentation files (the "Software"), to deal
#     in the Software without restriction, including without limitation the rights
#     to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#     copies of the Software, and to permit persons to whom the Software is
#     furnished to do so, subject to the following conditions:

#     The above copyright notice and this permission notice shall be included in all
#     copies or substantial portions of the Software.

#     THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#     IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#     FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#     AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#     LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#     OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#     SOFTWARE.

# """
name: 7. Scan Alerts Workflow Trigger
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Run Details'
        required: false
        default: 'PKScreener - Scan Alerts Trigger'
      installtalib:
        description: 'Is TA-Lib install required? (Y/N)'
        required: false
        default: 'N'
      targetPythonVersion:
        description: 'Target Python version: 3.9 , 3.10, 3.11 ?'
        required: false
        type: string
        default: '3.11'

  schedule:
    - cron: '0 4,10 * * 1-5'

jobs:

  Scans_Trigger:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: main

    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.targetPythonVersion || 3.11 }}

    - name: Restore Dependencies from Cache
      uses: actions/cache@v2
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install TA-Lib on windows
      if: ${{ inputs.installtalib != 'N' && startsWith(runner.os, 'Windows') }}
      shell: bash
      run: |
        python -m pip install --upgrade pip
        cd .github/dependencies/
        if [[ "${{ inputs.targetPythonVersion }}" == "" ]] ;then
          pip install TA_Lib-0.4.28-cp311-cp311-win_amd64.whl
        elif [[ "${{ inputs.targetPythonVersion }}" == "3.9" ]] ;then
          pip install TA_Lib-0.4.19-cp39-cp39-win_amd64.whl
        elif [[ "${{ inputs.targetPythonVersion }}" == "3.11" ]] ;then
          pip install TA_Lib-0.4.28-cp311-cp311-win_amd64.whl
        elif [[ "${{ inputs.targetPythonVersion }}" == "3.12" ]] ;then
          pip install TA_Lib-0.4.28-cp312-cp312-win_amd64.whl
        fi

    - name: Install Python Dependencies
      run: |
        pip3 install pkscreener

    - name: Trigger Scan alerts
      run: |
        python .github/workflows/workflowtriggers.py -s -s0 "S,T,E,U,Z,H,Y,B" -s1 "W,N,E,M,Z,0,1,2,3,4,5,6,7,8,9,10,11,13,14" -s2 "0,4,5,8,11,12,13,14,15,16,17,18,19,20,21,22,25,26,27,28,29,30,42,M,Z" -s3 "0,1,2,4,5,6"
      shell: bash
      env:
        GITHUB_TOKEN : ${{secrets.GITHUB_TOKEN}}

  Delete_Workflow_Run:
    runs-on: ubuntu-20.04
    needs: [Scans_Trigger]
    name: Delete workflow run
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
          
      - name: Delete this workflow run
        if: startsWith(runner.os, 'Linux')
        shell: bash
        run: |
          for id in $(gh run list --limit 100 --jq ".[] | select (.status == \"completed\" ) | .databaseId" --json databaseId,status); do gh run delete $id; done
          for id in $(gh run list --limit 100 --jq ".[] | select (.status == \"cancelled\" ) | .databaseId" --json databaseId,status); do gh run delete $id; done
          for id in $(gh run list --limit 100 --jq ".[] | select (.status == \"failure\" ) | .databaseId" --json databaseId,status); do gh run delete $id; done
          # Cancel runs queued or in_progress. See https://cli.github.com/manual/gh_run_list
          # for id in $(gh run list -w "13. Backtest for Generic" --limit 100 --jq ".[] | select (.status == \"queued\" ) | .databaseId" --json databaseId,status); do gh run cancel $id; done 
        env:
          GH_TOKEN : ${{secrets.GITHUB_TOKEN}}